security:
  access_denied_url: /access-denied
  password_hashers:
    # Spécifie que les mots de passe des utilisateurs qui implémentent PasswordAuthenticatedUserInterface seront hachés avec l'algorithme choisi ici
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: auto  # Symfony choisit automatiquement l'algorithme de hachage (généralement bcrypt ou argon2, dans le projet bcrypt est utilisé)
      cost: 15  # Détermine le coût de l'algorithme de hachage (complexité)

  # Configuration du fournisseur d'utilisateurs (d'où proviennent les utilisateurs pour l'authentification)
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User  # Indique que les utilisateurs viennent de l'entité User
        property: email  # Utilise l'email pour retrouver les utilisateurs dans la base de données

  # Définition des firewalls (protection des routes de l'application)
  firewalls:
    # Configuration du firewall pour les routes de développement, comme les outils de débogage et les ressources statiques (CSS, JS, etc.)
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/  # Ce motif couvre les routes liées au profiler, aux fichiers CSS, JS et images
      security: false  # Pas de sécurité appliquée sur ces routes (les utilisateurs peuvent y accéder sans être authentifiés)


    api_login:
         pattern: ^/api/login  # Cette route serait spécifique aux API (connexion via API)
         stateless: true  # Indique que l'API ne maintient pas de session (stateless)
         json_login:  # Configuration pour une authentification JSON (souvent utilisée pour les APIs)
             check_path: /api/login  # La route où les données de connexion sont envoyées
             username_path: email
             success_handler: lexik_jwt_authentication.handler.authentication_success  # Si la connexion réussit, la réponse JSON sera gérée ici
             failure_handler: lexik_jwt_authentication.handler.authentication_failure  # Si la connexion échoue, la réponse JSON sera gérée ici


    api_articles:
         pattern: ^/api/articles  # Cette route serait spécifique aux API (connexion via API)
         stateless: true  # Indique que l'API ne maintient pas de session (stateless)
         json_login:  # Configuration pour une authentification JSON (souvent utilisée pour les APIs)
          check_path: /api/articles  # La route où les données de connexion sont envoyées






             

    # Configuration principale du firewall pour toutes les autres routes
    main:
      pattern: ^/  # Cela couvre toutes les routes qui commencent par '/' (toutes les routes de l'application)
      provider: app_user_provider  # Utilise le fournisseur d'utilisateurs défini ci-dessus
      form_login:  # Authentification par formulaire
        login_path: app_login  # La route pour afficher le formulaire de connexion
        check_path: /login  # La route où les informations de connexion sont envoyées via une requête POST
        default_target_path: /  # Après une connexion réussie, l'utilisateur est redirigé vers la page d'accueil
      logout:  # Gestion de la déconnexion
        path: /logout  # La route pour se déconnecter
     


  access_control:
  # 🚪 Connexion libre
  - { path: ^/login, roles: PUBLIC_ACCESS }

  # 🔒 Déconnexion uniquement pour les utilisateurs connectés
  - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }

  # ✉️ Page de contact libre
  - { path: ^/contact, roles: PUBLIC_ACCESS }

  # 👤 Page profil uniquement pour les utilisateurs connectés
  - { path: ^/profil, roles: ROLE_USER }

  # 📰 Lecture des articles autorisée à tous
  - { path: ^/articles/\d+$, roles: PUBLIC_ACCESS } # Voir un article (ex: /articles/1)

  # ✏️ Création, modification, suppression d'articles → Réservé aux admins
  - { path: ^/articles/create, roles: ROLE_ADMIN }
  - { path: ^/articles/\d+/edit, roles: ROLE_ADMIN }
  - { path: ^/articles/\d+/delete, roles: ROLE_ADMIN }

  # 🔒 Accès complet à l'administration réservé aux admins
  - { path: ^/admin, roles: ROLE_ADMIN }

  # 📦 Accès libre aux assets (images, CSS, JS)
  - { path: ^/uploads, roles: PUBLIC_ACCESS }
  - { path: ^/images, roles: PUBLIC_ACCESS }
  - { path: ^/css, roles: PUBLIC_ACCESS }
  - { path: ^/js, roles: PUBLIC_ACCESS }

  
  - { path: ^/, roles: PUBLIC_ACCESS }
    







   